### ISSUE TITLE
Code clean-up

### ISSUE THREAD

**Issue by ehsan6sha** [functionland/photos#11]
Many un-used variable and states are created for thumbScroll between ThumbScroll and RenderPhotos and during development of other modules. All files need to be checked for unused variables and imports and cleaned.

**Comment by reubenjsinclair** [comment]
I'd be happy to work on this if that's okay? This would be my first contribution

**Comment by ehsan6sha** [comment]
> I'd be happy to work on this if that's okay? This would be my first contribution

Hi. Thanks for your help. Someone is working on this one, but feel free to pick any other one and that would be a great help

**Comment by emadbaqeri** [comment]
Hey there, is this one has been solved by anyone else? If not I would be happy to work on this.

**Comment by ehsan6sha** [comment]
> Hey there, is this one has been solved by anyone else? If not I would be happy to work on this.

Hi Emad
Not yet. your contribution is much appreciated. Please make sure you pull the latest code as we are actively developing.

**Comment by emadbaqeri** [comment]
@ehsan6sha Hi, I have removed all the unused imports and commented console.logs without considring there future usage. Is there anything elase that I have to do for this issue or task?

**Comment by ehsan6sha** [comment]
> @ehsan6sha Hi, I have removed all the unused imports and commented console.logs without considring there future usage. Is there anything elase that I have to do for this issue or task?

Thank you Emad. Appreciate your quick commit. I look today and merge if no issues.
