### ISSUE TITLE
Module renaming

### ISSUE THREAD

**Issue by ehsan6sha** [functionland/photos#12]
RenderPhoto and PhotoContainer and AllPhotos modules do not have clear names. Naming should be clearly reflective of what they do, links and references in other files should be changed and then the READ.ME should be updated. 
Affected files are:
- ./components/RenderPhoto
- ./components/PhotoContainer 
- - ./components/AllPhotos

**Comment by emadbaqeri** [comment]
Hey, I think I can work on this. Can you please assign this to me?

**Comment by ehsan6sha** [comment]
> Hey, I think I can work on this. Can you please assign this to me?

Hi Emad, sure. Thank you. which one you are thinking to start first. this one or Code Clean up?

**Comment by emadbaqeri** [comment]
I think  I should go with Code Clean Up.

**Comment by emadbaqeri** [comment]
I'm going to do this first and the Code Clean up

**Comment by emadbaqeri** [comment]
Actually naming a file or function is really hard but I have got renaming the most hardest in the world to do. I prefer to play chess with death angel :) by the way any idea about he component naming? I just really got stuck and nothing has came out. I actually have tried to track component actions and figured out the functionality of each but there is still nothing fancy, or not fancy just normal but logical.

**Comment by ehsan6sha** [comment]
> Actually naming a file or function is really hard but I have got renaming the most hardest in the world to do. I prefer to play chess with death angel :) by the way any idea about the this issue? I just really got stuck. I actually have tried to figure out the functionality of each but there is still nothing fancy, or not fancy just normal but logical.

TBH I was double checking this and realized this is not a good first issue lol It is very complicated, but thanks for taking time to look in to it. I think let's leave this one for now. If and whenever you have some free time I appreciate if you can help on one of the following issues?
- This one is easier: https://github.com/functionland/photos/issues/33
- This one might be harder: https://github.com/functionland/photos/issues/45

**Comment by emadbaqeri** [comment]
That's alright. I'm going to give a try on these you have mentioned and inform you as soon as I can. Tnx :)

**Comment by ehsan6sha** [comment]
I close this for now as module name change is trivial
