### ISSUE TITLE
Pre-commit hook for linting, type check & prettier code format

### ISSUE THREAD

**Issue by iarmankhan** [functionland/photos#32]
I was browsing through the project and found out there are not pre-commit hooks for said stuff. I'll be happy to create a PR about it if it's not a problem.

**Comment by ehsan6sha** [comment]
> I was browsing through the project and found out there are not pre-commit hooks for said stuff. I'll be happy to create a PR about it if it's not a problem.

Hi. That would be a great addition. I'll merge it.

**Comment by iarmankhan** [comment]
That's great. I'll start the work right away!

**Comment by iarmankhan** [comment]
May I know the use of code inside `unused` folder? Is it really unused code just sitting there, cause it contains the majority of eslint/types problems

**Comment by ehsan6sha** [comment]
> May I know the use of code inside `unused` folder? Is it really unused code just sitting there, cause it contains the majority of eslint/types problems

Yes, it's really unused code that I'm planning to delete

**Comment by iarmankhan** [comment]
Shall I delete it? I'm having real issues fixing the linting errors in it, it's better to delete it.

**Comment by ehsan6sha** [comment]
> Shall I delete it? I'm having real issues fixing the linting errors in it, it's better to delete it.

Yes, you can go ahead and delete it

**Comment by ehsan6sha** [comment]
@iarmankhan Thank you Armankhan for the pull request. I merge it today :)
