### ISSUE TITLE
BigInt is not defined and other errors for Dfinity libraries

### ISSUE THREAD

**Issue by ehsan6sha** [functionland/photos#59]
We are adding Dfinity support and right now their package does not support react native and you might get any of the errors below:
1- BigInt is not defined.
2- FileReader.readAsArrayBuffer is not implemented.
3- Buffer is not defined
4- window.open is undefined or other windows related errors
5- localStorage is undefined
6- readAsArrayBuffer is not a function
7- Code gets unresponsive and seems stuck

So we did custom polyfill to their libraries. To make it work, you need to replace the following files after you run yarn (and you need to do this if you run yarn again, not optimized but working to bake it into code):
(temp/ files mentioned are here: https://github.com/functionland/photos/tree/main/temp)

1- copy and replace "temp/transforms.js" to "...\node_modules\@dfinity\agent\lib\cjs\agent\http\transforms.js"
2- copy and replace "temp/index.js" to "...\node_modules\@dfinity\authentication\lib\cjs\index.js"
3- copy and replace "temp/index.d.ts" to "...\node_modules\@dfinity\auth-client\lib\cjs\index.d.ts"
4- copy and replace "temp/index-2/index.js" to "...\node_modules\@dfinity\auth-client\lib\cjs\index.js"
5- copy and replace "temp/index-3/index.js" to "...\node_modules\@dfinity\principal\lib\cjs\index.js"
6- Install 'react-native-polyfill-globals'
7- copy and replace "temp/leb128.js" to "...\node_modules\@dfinity\candid\lib\cjs\utils\leb128.js"

We need to bake these polyfills in the original code. Ideas are much appreciated.

**Comment by emadbaqeri** [comment]
@ehsan6sha Hey, thank you I have configured my IDE and replaced project files as you said now I can work on the issues.

**Comment by ehsan6sha** [comment]
For anyone who has the same issue in Dfinity, this is the whole process that worked for me:
(open file temp/instructions.txt)
I believe adding localStorage definition to the file below is not necessary as the create function seems to accept a storage parameter.

[photos/temp at main · functionland/photos (github.com)](https://github.com/functionland/photos/tree/main/temp)

To explain here is the changes I made:

1- Added BigInt defenition to the below files by adding this line to the top of each file:
```
if (typeof BigInt === 'undefined') global.BigInt = require('big-integer')
```
- ...\node_modules\@dfinity\agent\lib\cjs\agent\http\transforms.js
- ...\node_modules\@dfinity\authentication\lib\cjs\index.js

2- Added Buffer definition to the below files by adding this line to the top of each file:
```
global.Buffer = global.Buffer || require('buffer').Buffer;
```
- ...\node_modules\@dfinity\principal\lib\cjs\index.js

3- Added a localStorage definition to the below file by adding this line to the top of each file: (however it seems we can simmply pass it as a parameter in authClient.create)
```
if (!global.localStorage) {
  global.localStorage = {
    _data       : {},
    setItem     : function(id, val) { return this._data[id] = String(val); },
    getItem     : function(id) { return this._data.hasOwnProperty(id) ? this._data[id] : undefined; },
    removeItem  : function(id) { return delete this._data[id]; },
    clear       : function() { return this._data = {}; }
  };
}
```
- ...\node_modules\@dfinity\auth-client\lib\cjs\index.js

4- Added window defintion by modifying the below files by adding the below parts of codes:
- Modified AuthClientCreateOptions defenition to:
```
export interface AuthClientCreateOptions {
    /**
     * An identity to use as the base
     */
    identity?: SignIdentity;
    /**
     * Optional storage with get, set, and remove. Uses LocalStorage by default
     */
    storage?: AuthClientStorage;
	/**
     * Optional window object with open, addEventListener, removeEventListener, history.pushState, location.href. Uses window by default
     */
    windowObj?: any;
}
```
in file '...\node_modules\@dfinity\auth-client\lib\cjs\index.d.ts'

- Modified create function defenition to:
```
static async create(options = {}) {
        var _a;
        const storage = (_a = options.storage) !== null && _a !== void 0 ? _a : new LocalStorage('ic-');
		const windowObj = (_a = options.windowObj) !== null && _a !== void 0 ? _a : window;
        let key = null;
        if (options.identity) {
            key = options.identity;
        }
        else {
            const maybeIdentityStorage = await storage.get(KEY_LOCALSTORAGE_KEY);
            if (maybeIdentityStorage) {
                try {
                    key = identity_1.Ed25519KeyIdentity.fromJSON(maybeIdentityStorage);
                }
                catch (e) {
                    // Ignore this, this means that the localStorage value isn't a valid Ed25519KeyIdentity
                    // serialization.
                }
            }
        }
        let identity = new agent_1.AnonymousIdentity();
        let chain = null;
        if (key) {
            try {
                const chainStorage = await storage.get(KEY_LOCALSTORAGE_DELEGATION);
                if (chainStorage) {
                    chain = identity_1.DelegationChain.fromJSON(chainStorage);
                    // Verify that the delegation isn't expired.
                    if (!authentication_1.isDelegationValid(chain)) {
                        await _deleteStorage(storage);
                        key = null;
                    }
                    else {
                        identity = identity_1.DelegationIdentity.fromDelegation(key, chain);
                    }
                }
            }
            catch (e) {
                console.error(e);
                // If there was a problem loading the chain, delete the key.
                await _deleteStorage(storage);
                key = null;
            }
        }
        return new this(identity, key, chain, storage, windowObj);
    }
```
in file '...\node_modules\@dfinity\auth-client\lib\cjs\index.js'

5- Added the following imports to my file where I wanted to use Dfinity libraries
```
import 'text-encoding';
import 'react-native-get-random-values'
```

**Comment by krpeacock** [comment]
Would adding `big-integer` as a peerDependency and adding that bigint logic to our output be a good idea or a bad one?

**Comment by ehsan6sha** [comment]
> Would adding `big-integer` as a peerDependency and adding that bigint logic to our output be a good idea or a bad one?

I actually tried that approach and was still getting the same error until I added it directly to the top of dfinity files. I hope i wasn't doing it the wrong way but I tried multiple times

**Comment by ehsan6sha** [comment]
@Roman-Uholnikov Keyvan said you have an issue after installation, did you try this?

**Comment by Roman-Uholnikov** [comment]
indeed. I have an error while starting UI in the browser:
![image](https://user-images.githubusercontent.com/11457263/126185123-2783714d-cebb-4c2c-b0b7-ce08d0b0423f.png)

**Comment by emadbaqeri** [comment]
> indeed. I have an error while starting UI in the browser:
> ![image](https://user-images.githubusercontent.com/11457263/126185123-2783714d-cebb-4c2c-b0b7-ce08d0b0423f.png)
> 
> I suspect that the reason might be in the platform: I am using windows.

@Roman-Uholnikov Hey there, yes maybe it's because of your OS which is windows. I have setted up the project as ehsan said and it's working properly on my machine which I'm using arch linux

**Comment by ehsan6sha** [comment]
> > indeed. I have an error while starting UI in the browser:
> > ![image](https://user-images.githubusercontent.com/11457263/126185123-2783714d-cebb-4c2c-b0b7-ce08d0b0423f.png)
> > I suspect that the reason might be in the platform: I am using windows.
> 
> @Roman-Uholnikov Hey there, yes maybe it's because of your OS which is windows. I have setted up the project as ehsan said and it's working properly on my machine which I'm using arch linux

I just tested on Windows too and should not be OS. That's the besuty of expo lol
I am not sure why "browser" is here though. Maybe that is the keyword to issue

**Comment by ehsan6sha** [comment]
This is patched and will be applied automatically in 
https://github.com/functionland/photos/pull/63
