### ISSUE TITLE
Adding a settings menu

### ISSUE THREAD

**Issue by ehsan6sha** [functionland/photos#64]
Simply adding a settings screen can open new horizons for controlling backend, logins and more features. I am not sure whether it is best to have the settings as a drawer or a full screen yet. I believe we need to check how Google and Apple photos done this

**Comment by emadbaqeri** [comment]
Hi @ehsan6sha,
Can I work on this? I can put time on this at Weekend

**Comment by ehsan6sha** [comment]
> Hi @ehsan6sha,
> Can I work on this? I can put time on this at Weekend

Hi Emad. Glad you get some time now. Actually we now have a settings page. Are you intereted in creating an albums(Library) page? Maybe for now an albums page where it mimic the google photos by showing on device albums and server albums(without backend being involved using dummy json data) with ame design of Google Photos and then I can integrate it with a backend? Just a suggestion. Let me know if anything else is more appealing to you

**Comment by ehsan6sha** [comment]
@emadbaqeri  two  other things I have in mind are making settings page and menu holder for it(that also does login) aligned with the design of Google Photos, also dark theme addition. If none of these is of interest to you, Anything else you might think are interested in?

**Comment by emadbaqeri** [comment]
Do you have any UI sketches or something for this?

**Comment by ehsan6sha** [comment]
> Do you have any UI sketches or something for this?

Which one? Actually all designs are similar to Google Photos.

**Comment by emadbaqeri** [comment]
> > Do you have any UI sketches or something for this?
> 
> Which one? Actually all designs are similar to Google Photos.

Ok, got it, actually I have never used Google Photos, Time comes for me to install the Google Photos on my hone :)

**Comment by ehsan6sha** [comment]
> > > Do you have any UI sketches or something for this?
> > 
> > 
> > Which one? Actually all designs are similar to Google Photos.
> 
> Ok, got it, actually I have never used Google Photos, Time comes for me to install the Google Photos on my hone :)

Ah really? Do you use any alternative?

**Comment by emadbaqeri** [comment]
> > > > Do you have any UI sketches or something for this?
> > > 
> > > 
> > > Which one? Actually all designs are similar to Google Photos.
> > 
> > 
> > Ok, got it, actually I have never used Google Photos, Time comes for me to install the Google Photos on my hone :)
> 
> Ah really? Do you use any alternative?

Yeah I prefer to use the one that is installed on my phone by default, I like it because it is so simple and has a feature named `LOCK` which I can have locked gallery archives with password or pin, I'm using `huawei` phone.
